### ISSUE TITLE
Many cubes just show black

### ISSUE THREAD

**Issue by happydpc** [ReeCocho/ard-engine#3]
There are no cubes. I have used the examples' assets.
![1674061195653](https://user-images.githubusercontent.com/771776/213246178-19b0b636-a6bd-4302-8813-d311d4186da9.png)

**Comment by ReeCocho** [comment]
Oops! I changed how vertex attributes were handled and I forgot to update the examples. Test to see if it works on your machine now with the latest commit, and if it does I'll close the issue.

**Comment by happydpc** [comment]
Still show black, I have captured in renderdoc, shows this.
![1674100305218](https://user-images.githubusercontent.com/771776/213351211-4c15dd34-5578-4735-ba90-7dcafc5b6f77.png)

**Comment by ReeCocho** [comment]
When the application loads, press the M key. You should see your mouse cursor disappear. This means the free cam is turned on. You can turn it off by pressing M again. With the free cam on, you should be able to turn around and see the cubes and move around the scene with WASD.

I'll add this to the instructions and also make sure the cubes are centered on the camera by default.

**Comment by happydpc** [comment]
Have tested the updated many cubes. works well with culling. Nice job!

**Comment by ReeCocho** [comment]
Thank you for taking a look!
